# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassiveInfrared',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passiveInfrared', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SoundAnalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorSound', models.IntegerField()),
            ],
        ),
    ]
