# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound', models.IntegerField()),
                ('passiveInfrared', models.IntegerField()),
                ('idLamp', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='PassiveInfrared',
        ),
        migrations.DeleteModel(
            name='SoundAnalog',
        ),
    ]
