# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 04:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_auto_20160331_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
