# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 04:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_sensor_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
