# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_auto_20160331_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='idLamp',
        ),
    ]
